module Types where

type Weights = [Double]
type Input = [Double]
type Classification = Double
type ActivationFunction = Double -> Classification

-- A network description shows the makeup and topology of the network
data NetworkDesc = Empty
                 | Hyperplane { plusPoint :: Input
                              , minusPoint :: Input
                              , c :: Double
                              }
                 | Union NetworkDesc NetworkDesc
                 | Intersection NetworkDesc NetworkDesc
                   deriving (Show, Eq)

-- A network function is a function that can classify a point
type NetworkFunction = Input -> Classification

-- A network is a NetworkFunction and the description of the
-- underlying network. This should not be created by hand and instead
-- be generated by the makeNetwork function from the Network module
data Network = Network { f :: NetworkFunction
                       , net :: NetworkDesc
                       }

type TrainingInput = (Input, Classification)
type TrainingSet = [TrainingInput]
type PairedInputs = [[(TrainingInput, TrainingInput)]]

-- A function that will determine the order in which the points will be compaired
-- against one another
type PairFunction = [TrainingInput] -> [TrainingInput] -> PairedInputs


